/**
 * How often each run of three letters occurs in English prepared for Playfair, for scoring how much a
 * decryption looks like English.
 *
 * Counted from about 4.4 million letters of ten public-domain books from Project Gutenberg, as packaged in
 * the NLTK Gutenberg corpus: Jane Austen's Emma, Persuasion and Sense and Sensibility; G. K. Chesterton's
 * The Ball and the Cross, The Wisdom of Father Brown and The Man Who Was Thursday; Herman Melville's
 * Moby Dick; Maria Edgeworth's The Parent's Assistant; Sara Cone Bryant's Stories to Tell to Children;
 * and Thornton Burgess's The Adventures of Buster Bear. Only the letters were kept, uppercased, with J
 * counted as I, and then split into pairs with X fillers as {@link Playfair#encrypt} does, so that the
 * fillers a Playfair decryption contains count as English too. The runs of three letters were counted
 * across word boundaries.
 *
 * Each character below is one trigram, in order from AAA to ZZZ, and holds its log-probability,
 * rounded to the nearest quarter: the digit or letter at position k of 0-9 then A-Z stands for
 * log10(p) = -k/4. So THE, the most common trigram at about 1 in 54, is 7 (-1.75). Trigrams that never
 * occurred, including every one with a J, are Y (-8.5), well below the rarest one seen (R, -6.75).
 */
final class EnglishTrigrams {
    private EnglishTrigrams() {}

    /** Log10-probabilities of the trigrams, indexed by 676 * first + 26 * second + third, with A = 0. */
    static double[] logProbabilities() {
        String levels = LEVELS.replace("\n", "");
        double[] table = new double[26 * 26 * 26];
        for (int i = 0; i < table.length; i++) {
            table[i] = -Character.digit(levels.charAt(i), 36) / 4.0;
        }
        return table;
    }

    private static final String LEVELS = """
        YNNOYOOPPYRLIIYOYNKMYYRYPYGJLLGLMKFYOCLLDMRGGJHPJIJYGOGPDRREFYDHPLFYGGMEIYPGIR
        EEGGDGHGEYKGFFEHLGEEIGGGEYMYROYYRYOYYIOONYROLPNNPMYYGRYRFGROHYYIYRGYYGPEJYPGPY
        DPNLDOILGYRILIFNYEKMHYLIPYFMNNGNONIYYPJNHMYOKKHOLMMRKOMCJLIMNYNEGBJPYEGFLMMPYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYILMMDIPKFYYKLJIMYPJIMPKYKYEGGHDFJHDYEBEJEHMGEEHJEBJY
        EGJJCKJJEYNKIHEGLJGIHJJIJYDGC8EHDFDYEHGEDHJIDBGJEECNPRPYYIYLRYYNYKYPYINONPPYYY
        FNNLFNPJGYOHMNGERGFEJYLEMYYYYYYYYYYYYYYYYYYYYYHYYYYYEFFCCHFHDYEEEGFFJEECJHHEEY
        CFFGDFGDDYEFEEEEIGDBEHFDFPDFEFBFHBBYJEEGEFKFDCEIEDFPLNLJOLENMYYHOHNMRIFGYOMMOR
        HYYYBYYYEYYRYOFYYYRYNRYPIYEJLMHJOFGYJIKHGMOIHGNRLKKRHNNMLOPMKYPNNOMPRPKLYRKYOY
        FFIIFGJGEYMHHHFJLJDEJLGJJRLYYRHYYYJYYPYYMYRYYYNYYMJNYGFHYLJNNYKGMGYMYFHGPYNRKR
        LYONIPPOKYYKPPLRRNLMNRNNKYNYYPYYYOYYYPYYLYYNYYYYYYYYPYYYNYYYKYYYYYMYYOYYLYYYPY
        DHEFEEEFEYKEGFHHJEEDIIGEGROYYYPYYYNYYPYYLYYNYYPYYYYYPYYYRYYYPYYPYYNYYPYYYYYYYY
        KYYYKYYYMYYYYYLYYYYYRYYYYYLLMIFPHPYYRGNHLPPIJGPPPYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYPYYYPYYYYOYYYYYYYYYYYYFYYYCYYYFYYPYYGYYYYYGYYRFYLYYYMYYYJYYYYYOYYRYYNYYYOY
        YYYYNYYYPYYYYYKYYYYYYYYYYYFLYERLMMJYYHKHIYYGKFDHGGFYOYYYPYYYYYYPYYRYYPYYOYYYYY
        YYYYYYYYYYYYYYYYYYYYOYYYYYFYYYFYYYFYYYYYDYYYYYHYYYRYJLKOGMPLKYRMPOIMORMHJPLNOY
        JMPPJKYIKYYKNNJRYLKKPYMLNYYKHLYLNYIYOFLIKNYFFBYYYYJNYYYYOYYYKYYYYYRYYYYYYYYYYY
        KYYYMYYKLYYYYYMYYYYYYYYYYYYGYYYYYYYYYYYYYYYYYYYYYYYYFJIIIJJGHYNJHIIJNJGEMLHLLP
        YYYYYYYYYYYYYYYYYYYYYYYYYYOHJKMLLOMYKDEDPEYDFFEKLPMYOYYYMYYYNYYPYYNYYNYYLYYYPY
        IYYYHYYNJYYNYYHYYNYYIYYYYYPYYYLYYYMYYYYYLYYOYYRYYYYYEGGEHGKGEYMFGFEFNEDEJLFHIR
        NYYYNYYYNYYPYYMYYNYYPYYYYYOYYYNYYPYYYPYYOYYNYYPYYYYYCHHIDHIGDYLHFIEHNGFFGKFGIP
        FLNGFIKYPYRGKGGHYGGGPIPYYYYYYYYYYYYYYYYYYYYYYYYYYYYYFHIJEIJHGYNGIHGKOKFGKMHNIY
        FYYYFYYYGYYYYYFYYYYYGYYYNYLYYYMYYYNYYYYYMYYYYYNYYYPYLYYYOYYYOYYYYYMYYYYYYYYYYY
        GKJLMIKLIYRECCIIYFIHCGIIMPMYYYOYYPPYYNYYNYYLYRPYYYYYRYYYYYYYYYYYYYYYYYYYGYYYYY
        GYYYEYYREYYYYYFYYYYPGYYYIRKNMPLRRLLYRONNLLOYPKNYMYOYGJKLFJKHDYOFJKFLOJGIGPIILY
        RLNNLMYYLYYFGKMIYFHGYMYPYYYYYYPYYYMYYYYYPYYYYYRYYYYYLYYYMYYKMYYYYYNYYPYYYYYYYY
        YYFYYYYYYYYYYYYYYYYYYYYYYYIKKLMKNKJYYMLMINPNJINRINNYMYYYYYYYYYYYYYPYYYYYYYYYYY
        RGGHPGFHIYMEGCNHLEDEHHGODLHYYYCYYYIYYHYYGYYGYYEYYYEYFYYYIYYGKYYIYYEYYHYRIYYYRY
        IOPYFPRNGYYHPRGPYHMLKYNRLYDHFDGGHGHYNEGDGGKCDFIEHFINFYRYGYYYGYYHYYEYYEYYHYYYYY
        HYYYFYYOHYRJJRGYYGYYKYRYYYDYYYCYYYDYYYYYFYYYYYHYYYOYFIGDFEHHLYJGGBHKNGDDHHHJMM
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYIYYYIYYYYIYYYYYYYYYYYYGYYYERYYFYYYYYFYYYRYIYYPFY
        EPYYFPYYFYYYYPFOYFRYHRPYGYHYYRFYYYIYYYYYCYYYYHLYYYYYHIHKFDIIGYOHGCHIPGIHEHDGGL
        GYYYGYYLHYYHYYGYYGYYHYYYPYYYYYYYYYYYYYYYYYYYYYHYYYYYFJNPDYYKGYYYKYFPMNMYHYYNJY
        EIHJEIKDFYKHHJDGLKIDFLGIHYGYYYHYYAHYYRYYCYYHYYGYIYNYJKFYIPMYMYKHKGMFYHHIYYYYYY
        GYYYGYYYHYYYYYJYYYYYOYYYYYEYYYFYYDDYYYYYGYYIYYYYYYRYYYYDRYYYYYYYYYYYYYYYYPYRYY
        HJJIFILIHYLJIKEJOIHHMMHMMYYYYYOYYYYYYYRYRYYYYYYYYYYYJEECMFFHHYECFBIFLBCCGEGJJM
        FOPYDYYPHYYGYYEYYFMLDYPNGYCYLNERYEEYGFYYCRYELCFYYNKNBDFHDEFCBYLFEFCGJEDBEHDHGP
        GJJFYILHHYHFEDJFIHHFMGIGIKEMNNFIOLEYYFLRCNYEKFFRLJLYEMNLGMJKFYRGMLEMPEIJGPKJJY
        CPPRCYYRDYYYRPEPYPNPGROPLYGJHGIGFHMYJIGBGLPDDDGGHMRJYYYYYYYYYYYYYYYYYYYYYYYYYY
        KMNOHOPLGYYMOGMNYPIKYRNYNYDHIFDDLJCYKDILDGNMFEIGIDDPCFJKCILIDYNJGIDFNGFFFMHGFY
        DFCCCFEEDYJFFHCGJGDAGIEHGMKHILRBNILYYGLDYFYFMFFHJONRDKLLELMGFYREKNEKODHFGOKKKY
        YYYYYYYYYYYYYYYYYYYYDYYYYYBDDEADFDCYHEDECEJFBBGEDFBRBFEHCGICDYHGFGCDIICBDKECGR
        EHGIEIKADYNHGIBJMEFEELEEGPYYNNYYMYRYYNKFPFYIGJYNRRYYGYYYBYYREYYYRRGRYRYPMYYYRY
        BIKIDJLCDYMJHIDJOHGGLNJJKNGPEPAPYJHYYRLPMEKYPFLROYOYFHGHEIJFHYKIGJDINIFHLLEMMY
        RYYYJYYYMYYYYYNYYYRYYRPNPMRIEIOIIJFYMFFEOINEFEIHIHLRJYYYGYYYLYYJYYIYYIYYHYYYJY
        IYYYKYYILYYKYYFYYJYYKYPYYYJYYYHYYYIYYYYYIYYJYYKYPYPYFJFIFKMJIYOEIHJMLEGHLHFFLY
        HMNMFYPKGYYJMPHNRIKILPKLMYKYYYJYYOKYYLYYHYYIYYKYYYYYHYYREYYYDYYYYYIYYYYYJYYYNY
        JMFHFIGJRYNHIDJNYEFEJHKHYRYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYLYYYLYYYYLRYYYYYYYYYYY
        FRYYGYYYGYYYYYFYYYRYGYYYHYGYYYHYYYHYYYYYIYYHYYJYYYGYJYYYJYYYLYYYYYHYYYYYMYYYYY
        KLMNLILMKYYFMGHKYALJELLHYYIYYYHYYMKYYJYYIYYHPYKYYYPYYYYYYYYYYYYYYYYYYYYYKYYYYY
        FYYYEYYPEYYYYYCYYYYYJYYYNYIPJYHPYHHYNLKLGIRRPHGPLPMYHJMNDLNBHYPIKLGMPJIIKOIIIY
        YYYROYLYRYYDMHYJYHGIYYYRYPLYYYKYYYJYYYYYLYYYYYRYYYYYHYYYIYYFHYYYYYIYYLYYYYYYYY
        YYYYRDYYYYYYYYYYRYYYYYYYYYMNYPJPYLJYRRMREPYROKYYPONYYYYYYYYYYYYYYYPYYYYYYYYYYY
        RGIJNIGKDYNFHDNIOFGFLGIYJJIYYYGYYYLYYKYYJYYIYYGYYYIYIYYYLYYJMYYJYYHYYJYYLYYYYY
        JYYYIYYYJYYYYYHYYJYYLYRYRYGIJELIKHHYOGGEFJNEFELIHIJRJYYYJYYYIYYKYYGYYHYYKYYYYY
        LPYYHYYRJYYJYYJYYKNPNYRYLYFFKKEILIEYPHJJGJNKHBJMIIKYIJIJJJKKYYNJJDIKYGHFKEKPYM
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYOYMYYYLYYYYLRYYYYYYYYYYYFRYYGYYYFYYYYYGYYYYYLYYYGY
        GYYRHYYYJYYYYYHYYJYYJYYYIYHONYHNRNHYRNOPGNYPJLNPNYYYHILFIFKIFYRHLEFKNGJFGHIFMY
        IYYYIYYMKYYJYYJYYIYYLYYYYYYYYYYYYYYYYYYYYYYYYYJYYYYYEYYYCYYPGYYYYYEYYYYYJYYPIY
        GJIKHKLGGYMJJKFINLJFHNHJKYJYYYKYYCJYYYNYDYYJYYLYKYPYIRYPGPYYGYYHKHNGYHIKYRYYPY
        LYYYIYYYKYYYYYKYYYYYYYYYYYGYYYIYYGFYYYYYIYYLYYYYYYRYYYYYYYFYRYYYYYYYYYYYYYYYYY
        KNOPJMRMMYYPMOGLYPMLRRNYRYPYYYRYYYYYYYYYRYYYYYYYYYYYNFHBKHHHFYHCFBLDLCDAIBHPJK
        KYYYHYYYMYYKYYHYYJYYGYYYHYIYYYKYYJLYYLYYGYYKYYLYYYYYJYYYIYYYIYYYYYJYYJYYMYYYNY
        BCBCECDCCYFCBBDCH9ACGEBECMJYYYJYYYJYYKYYGYYIYYJYYYYYLYYYKYYYLYYLYRJYYIYYNYYRYY
        HYYYGYYYGYYYYYJYYYYYMYRYYYJKCHGJFJPYMDBBIEYGAELJKPYMYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYLYYYLYYYYLRYYRYYYYYYYYIRYYIYYYIYYYYYIYYYYYLYYYHYGYYYFYYPHYYYYYHYYIYRIYYPHY
        JMNKINYMKYKNMNGPYPKLNYKNPYHIGIIFKGHYJEEFHFREEGBJDHLYIYYYIYYOKYYJYYJYYIYYLYYYPY
        YYYYYYYYYYYYYYYYYYYYKYYYYYIYYYEYYYHYYYYYEYYYRYIYYYPYHLKNHMOGIYPKKMGJPOMHHPKNMY
        FGIJFGKCFYNFHHEJNIFGILGGHYYRLKLMJNYYYKGFYJYFFIYYYYYKLYYYJYYYKYYYYYMYYYYYYYYYRY
        GYYYHYYGHYYYYYGYYMYYYYYYYYYYYYYYYERYYYYYYYYYYYYRYYYYJKLIILMJJYPLJJGJPMHINPJLLY
        YYYYOYYYYYYYYYYYYYYYYYYYYYMHHKMLGKKYPFEDLKRHHFPMILLNJLRYFPYRIYYERYMYYJLYIYYLPY
        DKKKDKKCFYEIJLGJPKHFFMJKKPFHIHCHIFEYMGGEEILJFEJLHHHPILFDNGNLKYLGIDLPRGDEKFHKOR
        HKLMEGNGEYPIJJHLPMHFHRIGFYHKNMGLJBGYPMLFILYKKLHPLJNPEYYYIYYYLYYYYYHYYYYYOYYYYY
        MPRRONPPYYYPMMNYYRNMOYPLYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYDYYYJYYYYGRYYYYYYYYYYY
        GJKEDJLJEYICLLGMYMGGLIICERDGIIDHJGFYMIGHGELJEFGKGHJYCFDCCE9DDYDFFGEGHHCAFFEGGR
        NKLJIMMGHYJHPBNLRHIGELLOHYHKKLIKNJIYNIJMIIOIGHKPIIMYYYYYYYYYYYYYYYYYYYYYIYYYYY
        FHFGDGIHFYKFGJFHMIEFKJGIIPDEDFDEFCDYHFEEEEIGECGGEEHODFFHCGIACYLHFGFIMHDDFKCDDN
        POYHYYMYNYYMHIYNYJERYOYYYYHYYYCYYPFYRRRYJYYYPONYPYNYFYYYJYYKGYYYYYGYYNYYYYYYYY
        LNONHMOMHYPOLPJKYPLJPYLYMYYYYYOYYYRYYYYYMYYYYYYYYYYYIRYYGYYYJYYYRYKYYYRPOYYLYM
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYRHLLYKILOYRHLFYMPKIHPNLYNY
        KYYYIYYYMYYLYYKYYLYYIYYYJYKYYYNYYHPYYLYYJYYLRYMYRRRYMRYYLYYYKYYYYYKYYMYYOYRYPY
        EIIDHIKGGYOGHEHHNGFEJKIGHYIYYYMYYYKYYNYYHYYJYYLYYYYYLYYYNYYRNYYNYYKYYKYYOYYYYY
        IYYYGYYYHYYYYYJYYYYYNYYYYYKPJKLKPLPYMGLCNNRLIGNPLMYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYPYYYPYYYYNYYYYYYYYYYYYKRYYHYYYHYYYYYKYYYYYOYYYIYJYYYJYYYKYYYYYKYYLYYLYYYJY
        LYYYFYYYGYYYYYDYYYYYPYYYYYPOOYYFYMPYRPYHPNYJYOILRRYYKYYYMYYPMYYKRYLYYLYYMYYYYY
        YYYYYYYYYYYYYYYYYYYYMYYYYYMYYYKYYYMYYYYYKYYYYYMYYYYYGJJLJKLHIYNKJLHLMMLHKMIKLY
        MYYYMYYFLYYYYYGYYMYYNYLYYYYYYYYYYYYYYKNLYIYRMRYYYYYYOYYYKYYYNYYYYYOYYYYYYYYYYY
        HYYYJYYHHYYYYYKYYNYYYYYYYYYYYYYYYYYYNYYYYYRYYYYYYYYYKMNMJMNLLYRKMOGMROLKPOLYPY
        YYYYYYYYYYYYYYYYYYYYYYYYYYKHEEOIHJFYJHFCNHREDEFJGMFJJRRREPYYKYRKPOHYYHMNGYOYKY
        HYYYKYYILYYKYYFYYIYYJYYYPPFEGIFGHEFYKGFDFHLFFFIKGIHRCFEDHEFFEYKGEDEGKFCCJGEFFR
        FHIJIJLHFYNJJKGINHHGILHJKYJYYYIYYOJYYKYRHYYIYYMYRYRYGYYYFYYYGYYYYYHYYYYYKYYYYY
        FHFHEFEJNYDKGCGHLKECJFKJPHYYYYYYYYYYYYYYYYYYYYYYYYYYIMNOGMOKGYYMNIIOYNIINYJYLY
        EFHHEHHFEYJYGGEHMHFEIKGHEYGNNPGPPPIYPKPLFRYJKLKPNYHYKYYYGYYYKYYYYYFYYYRYMYRYYY
        HJGIOEHKKYYLKDEIKFFGEFDEIRIMPPINPJJYRILPIRYHLKJYMPLYYYYYYYYYYYYYYYYYYYYYKYYYYY
        JYYYGYYRIYYYYYIYYYYYKYYYKYFJJKFJMGHYMJIKFIMLJFHOHKJYGKLMFLNCGYPLLLENNIIIJNJJIN
        KJGHGMLYMYKOHGOJYJHGYOYLPYLYYYFYYYJYYYYYKYYYYYRYYYYYEYYYHYYGGYYYYYIYYLYYYYYYYY
        YYYYYYYYYYYAYYYYYYYYYYYYYYDFFFGFGFEYIGFHEGKGEDHJFJJPYYYYPYYYYYYYYYPYYYYYYYYYYY
        HIFELHFIFYEEHBMIODEEJLHIEJHPONENPMIYRGNOIPRIJLGYNMIYJYYYLYYKPYYLYYIYYKRYMYYRYY
        MYYYIYYRKYYYYYIYYLYPMYYYPYDFGDHFIFEYKFFCEHJDDCHIFGHYKYYYLYYYKYYLYYFYYHYYLYYYYY
        MYYYMYYYLYYKYYIYYLYYOYYYYYIYYYFYYYGYYYYYIYYYYYMYYYRYINIGJJEKPYNEJCLOYGDFKOKJPM
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYNYYYMYYYYMYYYYYYYYYYYYJYYYJYYYJYYYYYJYYYYYNYYYIY
        FYYYGYYYIYYYYYHYYKPYJYYPJYKOOPHOYOJYYLNPGPYPMMYYOPPRNIJHPGNLLYILFDIMYCDEEGMIYY
        EJNNFLPIIYNENNFOYGIGIYMNNYYYYYYYYYYYYYYYYYYYYYJYYYYYHKIKGIIKJYHNJLJIRNDJLNGMRY
        GKKMELPHIYRKKMGKNLMGGOJLKYKYYYLYYDKYYYYYFYYKYYLYLYYYYYEKMLNYYYYIKHYIYHDIYYYYYP
        OYYYIYYYNYYYYYOYYYYRRYYYYYIYYYIYYFGYYYYYKYYNYYYYYYYYYYYYYYYYYYYYEYYYYYYYYRYYYY
        IHHGIGIHIYMHHJGHNJFILLHNPYYYYYYYYYYYYYYYRYYYYYYYYYYYNFGHMGGGIYJEFCNGLFEDJHGNIR
        HYYYFYYYKYYIYYHYYIYYEYYYGYGNYYBYYFFYPGYYEYYGYHIYRYGYCEEGCEFCCYHEDFDEIECBFHDGFR
        DGFCGGHGEYKFFFEHJDCEJDDEFOGYRYGYYYFYYHRYEYYGYYHYRYYYCEFFDEHDDYJEEGDFJECBFHEHGP
        EYYYDYYYDYYYYYGYYYYRJPYYNYGJGIHGEIPYKJGCFKMJEDHIINRKYYYYYYYYYYYYYYYYYYYYYYYYYY
        HJILHJLHFYYHJHHLRLGHMLIPHYGYRYGYYYGYYYYYGRYYYYJYRYDYFRYPGYYYGYYYYYGRYHYYIYYYGY
        IRRPERRRGYNYRYFPYRNOLYORJYHGGGIDJHGYMGFEHHNDGAEICIKPGYYYHYYLJYYHRYHYYGOYIYYYRY
        YYYYYYYYYYYYYYYYYYYYGYYYYYIYYPFYYPHYYYYYHYYYYYJYYYKYEGGJEHKEEYLIIJEGLJIDFKEIJY
        DGGHCGIACYIEGIBHMEDFFJEFFRIRPRHLLYJYYMHGLHYJHGYYYYYRHYYYFYYYGYYYYYIYYYYRMYYYLY
        FRYYFYYDEYYYYYHYYKYYYYYYYYYYYYYYYYHYYRMDYYRYOPYRYYYYHHIIHIJIIYLJHJEIMIHFLLHLKY
        OYYYLYYYOYYYYYPYYYYYRYYYNYRIGGRIJJMYIGIFPINFFEMJJNMYGJPMCPPMGYYGPPHYRIGJHKOJIY
        GYHYGYYHHYFIYYFYRIRIIYRHPYFHIHFHIFFYLIIHEJMHGGGMHIEYHMMJRMONLYPJIHKNMMFIMHMHNY
        DFFFEFGDEYJFEHFFLFEBHIFFGPIMPOFNLNGYPKMJGPYHJLJRLLJYELLKEMLLEYPLJGHLYRJJJNKLJY
        JMFHJKMKPYNGIDJNYKFGJOKLYYYYYYYYYYYYYYYYYYYYYYYYYYYYGKKLDKMHFYRKKHHKOMGIKNJYJY
        GLLDEKMKEYKFKLEMYLIIGHKFIYDGIJBGKFEYNJGJFEOGGEFLHGGYDFEDBECEDYJDFHDHJHCBIFEHGL
        KJKELILJKYEGGEYINFHGJLJLNNGLNMDMNHGYLFKNGGRGIIHYKHKYYYYYYYYYYYYYYYYYYYYYIYYYYY
        DGFDBGFEEYFEDEFGKGDBHKEGERFMJPCMNGFYNJILGGNPFDGPJFKYEEGHEGHAEYHGGJFHJGEEHJGFHR
        EFFFIHCFFYGBFCHGLBCBKJEKIPJYYYCYYYHYYYYYJYYYYYYYYYYYDGGGDHJEDYMFGCGILIEEJJGGHY
        KMMOKLPLKYYNNPBORPLMRPLYOYGLLMHKNJIYPMINEMRMHJOPJMPYPYYYJYRRPYYNYYPYYYPRYYPROY
        MJHJPLIMFYOGKEOGODEFHLKNHYMYYYIYYYPYYNYYLYYMYYJYYYKYLYYYRYYMPYYNYYKYYMYYOYYYYY
        MYYYMYYYMYYYYYKYYMYYNYYYYYEKEEIKKJIYPHKDFLICHGNMJIJPNYYYMYYYMYYNYYIYYJYRRYYYYY
        MYYYOYYYOYYPYYNYYMYRPYYYYYHONRGRRPGYYPRRJYYKNNMYNOIYJPGHGMJOYYKHMEJINGIFMNNPYR
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYLYYYLYYYYNYYYYYYYYYYYYDYYYDYYYFYYYYYHYYYYYIYYYGY
        JRYYKYYYNYYYYYLYYMYYMYYYKYPYYYMYYYOYYYYYKYYYYYRYYYYYROIMIHPNFYGGKDGJYFDHGKGGYM
        JYYYFYYRHYYIYYGYYIYYOYYYHYYYYYYYYYYYYYYYYYYYYYMYYYYYFYYYDYYYEYYYYYCYYYYYIYYYMY
        HKKMIKMIHYOLKMILPMKGKPJKJYFKLNGLOFGYRJLMGNYLJJIRKJIYYIYKYKMYRYYGLIYJYGIFYYYYYK
        RYYYOYYYPYYYYYOYYYYYYYYYYYIYYYLYYIIYYYYYLYYMYYYYYPYYYYYYYYYYPYYYYYYDYYYYYYYYYY
        JLLLKLOKJYPMLNINYLLJRPKRNYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYRYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYRYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYPYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYRYYYYYEYYYEYYYDYYYYYHYYYYYRYYYPYYYYYYYYYYYYYYYYYYYYYYYYYYY
        RYYYYYYPYYYYYYYYYYYYYYYYYYYRYRYYYYPYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYMFEFKGFIEYKDGBIFNFEDJGFLGJGYYYERRNIYYIRRGYYFLNFRNRHY
        FYYYFRYEIYRHYYEYYHPMGYYYKYEHJLEHKHEYOGIJFJNHEFJMGLIYBFDCEEFEDYKDDDEEGFBCIEDEER
        FORYFYYNHYYIYYFYRFNMGYNNYYHYYYEYYMHYYIYOGPYHOMIYPRKYDYYYDYYYEYYYYYGYYYRPHYPYMY
        EGEGCGEIMYIGGCEHRLEDHFILRHYYYYYYYYYYYYYYYYYYYYYYYYYYHKLLGKMJHYRJKGJLPLGIMNJYMY
        GLNFFPPLFYYNNOGNYPIJKYKPFYEKLMEKNJEYPINLFMRGHIHPHMGRGFLMEINJEYPKJMFLPLHHKRINLY
        FFGGLDIJIYGGCEGEPFEFCFDGILGNORFNPKJYPGPPFPRFKMIRNROYYYYYYYYYYYYYYYYYYYYYHYYYYY
        GYYYFYPPFYYYYYGYYYPYJYYYGYDGGHDHIEEYKHGIDGKIHCFJFHJREIKLFHLBEYPHIIDKRHGIFNGIFN
        MIHIGLIYHYYIHFNGYNFHYPYRRYGYYYFYYYGYYYYYIYYRRPOYYYPYEYYYFYYEEYYYYYGYYJYYYYYYYY
        YYYYPYYYMYYYYYRYYDYPYMYYYYFFGGGGHGFYJGFIEGLHFEIJFKJYYYYYPYYRRYYYYYPYYYYYYYYYYY
        LFFGNFFICYIDEBNFLEEDIGELDRFRRPERRRIYYIRRGRYGRREYPRGYEYYYGYYFGYYHRYDYYFNPHYPRNY
        GYYYFYYYGYYYYYGYYHYYJYNYNYDGEDDGIFEYJCFDFGHDEDIFFDFPEYYYGYYYGYYIYYEYYFYYHYPYKY
        IYYYIYYOIYYIYPFYYFYYIYYYYYCJJLAIKJDYNJHJCKRIIGGLGJIYHFGDGFFHNYJFFCEJOEEDHHIHYJ
        YYYYYYYYYYYYYYYYYYYYYYYYYYKMNNFKOKGYYMKIKMOMJJKYKRHYFYYYFYYYEYYYYYFYYYYYJYYYGY
        DNPPFNYMEYYPPRERRHLLGYMPGYGYYYFYYYJYYYYYDYYYYIJYYYYYGGGHICIGGYKECDFGLEGFFGFGJR
        ELRYDYYIEYRGRYEYYEMNHYOYLYYYYYYYRYYYYYYYPYYYYRFYPYYYHYYYEYYPHYYYYYHYYYPYIYYYYY
        FHIJEILFEYLIHJEHMKYFGMGHJYBFFGCGHBCYJFGGBGLCEFEJFFGPGFDGIHIYHYYHGEREYDFLYMRYYY
        JYYYFYYYHYYYYYIYYYYYPYYYYYEYRYDRYDEYYYYYFYYIYYJYYYYYYYYYYYYYRYYYRYYYYYARYRYYYY
        JLKNHMNLKYPJFMEMYLJJPPLOPYYYYYNYYYRYYYYYPYYYYYYYYYYYLEFHOGFHDYECGBNGLEDDIIHMGP
        HYYYDYYYJYYIYYIYYHYYFYYYGYFORYIRYEKYYIYYEYYHRPIYPYPYHYYYFYYYGYYYYYFYYIYRKYNYLY
        EHGBGGIGGYMDECGGKAEGIFGFJPGYYYHYYYFYYJYYEYYFYYGYYYYYIYYYHYYNIYYJYYGYYHYYJYRYYY
        9HHH7HHFAYLHFIBHKDEDFKFFFRFIDGFFHGNYJDDBBJKGCDIFGLPLYYYYYYYYYYYYYYYYYYYYYYYYYY
        RYYYJYYYJYYYYGYYYRYYYYYYYYFRYYCYYYFYYPYYFYYYYYJYRODYEPRRFYYYGYYRYYFYYGYRGYYYGY
        IYYRGYYYHYYPYYEYYYYNLYYYYYDCEEFCECFYGEDCEEJDDCEHEEGPGYYYGRPLIYYHYYHRYFNYIYPYPY
        YYYYYYYYYYYYYYYYYYYYHYYYYYDYYYDYYPEYYYYYEYYYYYEYYYFYEGGIEHJDFYKHHHDGKIIEFKFHIY
        GYRPDYYCGYYEYRDPYILYJYJPIYGHIGIKLPMYPJIFJFYCHJYRYYYYJYYYHYRYJYYYYYKYYYYYOYYYRY
        CYYYEYYDDYYYYYDYYKYYYYYYYYYYYYYYYYYYYYYYYYRRYAYYYYYYFIIJGHJHGYLIIJDINJHGMNGKJR
        POYPNRYRYYYYYYYYYYOOYYYYYYYJLIYMJNGYKEMGYLPEIHYNNYLYLHPLIOYMGYRGJOKRYMIGJROHLY
        GYJPHYYCJYFMYYIYYKYHMYYIHYILMHFNHLHYOKMNGPYLJKNNLHJYIJKGHKHJJYRHJGILPIFHMJJHLP
        LYYYLHYYKYYNYYIYYLYMOYYHRYJOPRINIBKYYKMNJPYMNNKYNIRYFYYYIYRYMYYYYYKYYYPYNYYPRY
        KOHJHLPLRYNHLGMMYGFEMKLRYMYYYYYYYYYYYYYYYYYYYYYYYYYYRYYYIYYRNYYYYGYYYYYYYYYYYY
        EJIBHJIJGYJFJIHJPKHFNLIEJRGGNPGLNNHYYOIKHGRKGKHPLJKYGJFCGHEIFYHHJIHILIGDJMHINR
        YLPIYKPLNYRPPKYPYKONIPNYKYGJLMGJNHGYPHKMEGOIIFKOIGKYYYYYYYYYYYYYYYYYYYYYLYYYYY
        EGFGCGHGEYJHHDGFMHDFLIHHGPEHHICHHFEYJFIHHGMJHCGKHHIPEGHHEGIDDYKGGGEHLHEEGKFEGR
        YYYYYYYYYYYYYLYNYYOYYYYYYYOYYYJYYYKYYYYRPYYNYYYYYYYYIYYYHYYIGYYYYYHYYMYYYYYRYY
        OPRRYYRROYYYYYRYYYYOJYYYRYMPRYKPPNMYYROPJRYRMLPROYPYPYYYYYYYYYYYYYYYYYRYYYYKRK
        PLJLRPIOHYYGNFYLYHIHLRORRYYYYYYYYYYYYYYYYYYYYYRYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYEEHDIHHFFYJFFCGHLADEIKGIGPYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYRYYYYYYYYRYYYRYYYYYYYYYYYYYYYPYYYYYHLGGHPKYMYYFYEGRYIFGMIRMYR
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYRYYYYYYYYYYYYYYYYYYYYYYYYYPYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYPYYYYYYYYYYYYYYYYRYYYYYRYYYYOYYYYYYRPJYRYYYFYKGNKPYYIPJGRLPIY
        YYYYYYYRYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYRYYYNYYYPYYYYYRYYYYYYYYYYY
        RYYYYYYYYYYYRYRYYYYRYYYYYYYYRYYYYMYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJRRRYYYYYYYYYYY
        YYYYYYYYRYYYYYYYYYYYYYYYYYYYYYRYYRRYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYPYYYY
        LMMONNPLMYYMNPMPYNLMRONPRYYYYYYYYYYYYYYYYYYYYYYYYYYYYKKKYLJMGYIEJEYLPDAFRILLDY
        KYYYHYYYNYYMYYKYYLYYIYYYKYIYYYNYYLPYYMYYIYYKYYMYYYYYJOPPIRPPJYYNPPIPYKMONYORMY
        FKHFGKKGJYLDHELJNCFIMFHGKYJYYYLYYYLYYLYYIYYJRYJYYYYYMYYYMYYYNYYLYYKYYLYYNYYYYY
        CYYYCYYYCYYYYYCYYYYYMYYYFYKOHHMGJKYYMCIDOLRLEBLLMRYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        PORRMOYPLYYPYMYORYNPYYKYYYJNPYGNRYIYYYPRJYPYKNNRORIYIYRYJYYYIYYYYYIYYJYYIYYYKY
        GHIIHHKGGYNJILGIMJGFJKHLKRJJJJJGKJKYLIFFGIODIICKKFKYKYYYKYYPNYYLYYKYYKNYMYYYRY
        YYYYYYYYYYYYYYYYYYYYKYYYYYJYYYHYYYGYYYYYHYYYYYMYYYPYHKLMIKOHIYYKKKHJRMLHJOJLLY
        LYYYKYYELYYYYYGYYLYYLYMYRYYYYYYYYYYYYYPJYJYPMYYYYYYYNYYYJYYYPYYYYYKYYYYYYYYYYY
        KYYYKYYHKYYYYYLYYOYYYYYYYYYRYYYYYYYYYYYYYYYYYYYYGYYYLRYRKYPYYYYRRRHYYYPPYYPYYY
        YYYYNYYYYYYYYYYYYYYYYYYYYYYPHPYNLRRYYLHHYORMKKYPRYPYLYONIOYMJYPKPPLRYMLMLYMPLY
        IYYYFYYKIYYHYYGYYNYYHYRYYYIPPYFYYNGYPHRPGRYHLLKPNRKYGJIEYILIHYHFFDJFHGHFMGIGIK
        HLNNFYPKGYYJMOHOPIKILPKKNYKYRYHYYYJYYJYYJYYJPRNYYYMYHYYYFYYYGYYYYYJYYYYRLYYYRY
        LLKMJMNNNYRMKJHPYPIJMNNKYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYPYYYYMYYYYYYYYYYYY
        EFHHEHIFEYJYGGEIMIFEIKGIEYFYYYGYYRIYYYYYGYYKYRJYRNJYJYRPERYPGYOPRYFPYYNOLYORJY
        KJKDPHLKLYEGGFYJNFIGJLKLNPIYRYERYRHYYGYYGYYGYYOYYYHYYYYYYYYYYYYYYYYYYYYYKYYOYY
        GRYYFYOPEYYYYYGYYYPRJYYNGYEHIJEHKFEYLIHJEHLKPEFMGHJYGNNJDNPCFYYEJMDMPGKKJOIKHY
        YPYYYYYYYYYLPLYNYLMYYYYYYYRRYYPYYYMYYYRYYYYYYPYYYYPYJYYYJYRHJYYYYYLYYPYYYYYPYY
        YYYYYYYYRYYYYYYYRYYYYYYYYYMYYYIYPYPYYYYYHYYYYPYYYYYYLYYYNYYYNYYKYYRYYYYYYYYYPY
        YHHIYHHJLYNFIDYINFFGLKIYLRIYYYEYYYJYYJYYFYYHYYFYYYHYFYYYJYYHJYYIYYEYYIYYJYYYPY
        GPYYFYYYFYYYRRGYYIYYKYPYOYFJKGOKKJIYPGIHKLLIEFMHJHIYGYYYHYYYHYYJYYFYYGYYJYYYYY
        IYYYIYYYIYOIYRGYYHYYJYYYYYEYYYEYYYGYYYYYGYYYYYIYYYNYHLJIJILIOYKJHDJNRKGFJLJNRY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYKYYYIYYYYHYYYYYYYYYYYYHYYYGYYYFYYLYYFPYYYYJRYLNY
        FKYREYYYGYYYONFIYHYYGYYPIYIYJOHYYYJYYYYPFYYYRPMYYPYYMIKLREPJLYNJNEPJYGOHAJIPYY
        GYYYHYRKIYYHYPHRYGPLIYRYPYYYYYYYYYYYYYYYYYYYYYIYYYYYHYYPFPYPIYYYYYHYYPRNHYRYYY
        EIIJEJJFFYKIHKFHLKIEGLHIKYHYRYIYRCHYYYYYDYYHYRIYIYOYYRYYYYPYYYYPOGYIYMJPYYYYYY
        KYYYIYYYJYYYYYKYYYYYPYYYYYFYYYEYYEFYYYRYGYYJYYYYYYYYYYYYYYYYPYYYYYYYYYYYYYYRGY
        MYYYIYYYPYYYYYHYYYYYYYYYYYPYYYOYYYYYYYYYRYYYYYYYYYYYPIPPPPOONYYOPOOOYJNLYYMROY
        YYYYOYYYYYYYYYYYYYYYRYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYRYYYRYYYYYYYYRYYYYYYYY
        JMNHPMRLLYPLKJKNYNKJNPLONYYYYYYYYYYYYYYYRYYYYYYYYYYYYYYYYYYYYYYYYYRYYYYYYYYYYY
        RYYYPYYYYYYYYYYYYYYYYYYYYYYYYYNYPYYYYNPIRRYYRRYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYRYYYJYYYMYYYYYYYYYYYNYYYPYYYYYYYYYRYYYYYRYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYOPORYYYYPYJOYYMYRYYYPYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYRYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYRYPYYYYRRYYYYYPRYYYYYYPYYY
        RYYYYYYPYYYYYYRYYYYYOYYYYYYYYYYYYYYYYYRYYYYMYYYYYYYYYYYYYYYYYYYYYYRYYYYYYYYYYY
        RYYYYYYPRYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYJNPOPRPYPPYYMMRORYPNOYPNYYY
        KYYYPYYYNYYKYYPYYYYYYYYYPY""";
}
